version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - unused
    - gocyclo
    - funlen
    - lll
    - gosec
    - nilerr
    - errorlint
    - bodyclose
    - noctx
    - testifylint
    - misspell
  settings:
    funlen:
      lines: 85
      statements: 75
    lll:
      line-length: 125

formatters:
  enable:
    - gofmt
    - goimports
