version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - unused
    - gocyclo
    - funlen
    - lll
    - gosec
    - nilerr
    - errorlint
    - bodyclose
    - noctx
    - testifylint
    - misspell
    - nolintlint
  settings:
    funlen:
      lines: 85
      statements: 75
    lll:
      line-length: 125
    nolintlint:
      require-explanation: true
      require-specific: true

formatters:
  enable:
    - gofmt
    - goimports
